blog/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
  end
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true

    has_many :comments
    #belongs_to :post
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all        
    end

    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def destroy
        
    end

    def create
        @post = Post.new(post_params)
        if post.save
            flash[:notice] = "Post created!"
        end        
        redirect_to :index unless request.xhr?
    end

    private 
        def post_params
            params.require(:post).permit(:title, :body)
        end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag('bootstrap.min.css')%>
    <%= stylesheet_link_tag('bootstrap-theme.min.css')%>    
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

blog/app/views/posts/_post.html.erb
<div>Title: <%= post.title%></div>
<div>Body: <%= post.body%></div><br/>

<%= link_to "Comment this!", new_post_comment_path(post.id), class: 'btn btn-default' %>

blog/app/views/posts/_post.html.haml
%div
  = link_to post.title, post_path(post)
%div
  Body: #{post.body}
%br/
= link_to "Comment this!", new_post_comment_path(post.id), class: 'btn btn-default'
= link_to "delete", post_path(post.id), method: :delete, class: 'btn btn-default'

blog/app/views/posts/create.js.erb
$("body").html("");
$("body").html("<%= render 'post', post: @post %>");

blog/app/views/posts/index.html.erb
<h1>Posts</h1>

<%- if @message %>
    <div class="alert alert-success">
    <%= @message %>
    </div> 
<%- end %>

<%- @posts.each do |post| %>
    <%= render "post", post: post %>  
<%- end %>

blog/app/views/posts/index.html.haml
%h1 Posts
- if flash[:notice]
  .alert.alert-success
    = flash[:notice]
- @posts.each do |post|
  = render "post", post: post

blog/app/views/posts/new.html.erb
<div class="row">
<%= form_for @post, url: {action: "create"}, :html => {:class => "form-horizontal center"} do |form| %>
    <div class="form-group">
        <%= form.label :title, "Title:",class: "col-md-4" %>
        <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :body, "Content:", class: "col-md-4" %>
        <%= form.text_area :body, size: "60x12", class: "form-control" %>
    </div>
    <%= form.submit "Create", class: "btn btn-default"  %>
<% end %>
</div>

blog/app/views/posts/new.html.haml
.row
  = form_for @post, url: {action: "create"}, remote: true, html: {class: "form-horizontal center js-form-new"} do |form|
    .form-group
      = form.label :title, "Title:",class: "col-md-4"
      = form.text_field :title, class: "form-control"
    .form-group
      = form.label :body, "Content:", class: "col-md-4"
      = form.text_area :body, size: "60x12", class: "form-control"
    = form.submit "Create", class: "btn btn-default"

blog/app/views/posts/show.html.haml
= render "post", post: @post